"""
plot_banerjee_network_variation.py

Network-variation grouped-bar charts: Proposed vs DAuth vs Banerjee
N = 30, 50, 80, 100, 120  (20% newly-joined devices, 10 seeds each)

Reads summary.csv from each scheme/size folder (generated by run_network_variation.py).
Sums Enrollment + Authentication + Key Exchange per-device means for each bar.
Combines CI95 in quadrature: sqrt(ΣCI_i²).

Two panels:  Total Energy (mJ)  |  Total CPU Time (s)
Output:
  Results/COOJA-Simulation/Banerjee-Comparison/banerjee_network_variation_energy.png
  Results/COOJA-Simulation/Banerjee-Comparison/banerjee_network_variation_cpu.png
  Results/COOJA-Simulation/Banerjee-Comparison/banerjee_network_variation_combined.png
"""

import os, csv, math
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# ── Paths ─────────────────────────────────────────────────────────────────────
REPO = "/home/apex/contiki-ng/examples/Codes-For-COOJA"
OUT  = os.path.join(REPO, "Results", "COOJA-Simulation", "Banerjee-Comparison")
os.makedirs(OUT, exist_ok=True)

SUMMARY_DIRS = {
    "Proposed": os.path.join(REPO, "Revised-Anonymity",
                             "Simulation results", "network-variation"),
    "DAuth":    os.path.join(REPO, "Results", "COOJA-Simulation",
                             "DAuth-Sweep", "network-variation"),
    "Banerjee": os.path.join(REPO, "Banerjee-Scheme",
                             "Simulation results", "network-variation"),
}

SIZES  = [30, 50, 80, 100, 120]
PHASES = ["Enrollment", "Authentication", "Key Exchange"]

# ── Scheme style ──────────────────────────────────────────────────────────────
COLORS  = {"Proposed": "#2C6FAC", "DAuth": "#7E5BA6", "Banerjee": "#C0392B"}
HATCHES = {"Proposed": "///",     "DAuth": "...",     "Banerjee": "xxx"}
SCHEMES = ["Proposed", "DAuth", "Banerjee"]

# ── Global chart style ────────────────────────────────────────────────────────
_STYLE = {
    "font.family":       "Liberation Sans",
    "font.size":         13,
    "axes.titlesize":    14,
    "axes.titleweight":  "bold",
    "axes.labelsize":    13,
    "axes.spines.top":   False,
    "axes.spines.right": False,
    "axes.linewidth":    0.7,
    "xtick.labelsize":   12,
    "ytick.labelsize":   12,
    "xtick.major.size":  0,
    "legend.fontsize":   11,
    "legend.framealpha": 0.9,
    "legend.edgecolor":  "#cccccc",
    "grid.color":        "#e5e5e5",
    "grid.linewidth":    0.6,
}


# ── Data loading ──────────────────────────────────────────────────────────────
def load_summary(scheme, n):
    """Return (total_energy_mJ, ci_energy, total_cpu_s, ci_cpu) for scheme at size n.

    Computes: sum over all devices, averaged over seeds.
      total = Avg_Energy_mJ × n_devices  (summed across phases)
      CI    = CI95_Energy_mJ × n_devices (combined in quadrature across phases)

    This gives the total network cost — all devices combined — as seen averaged
    over 10 seeds, matching: for each seed compute sum_devices; then average over seeds.
    """
    path = os.path.join(SUMMARY_DIRS[scheme], f"N{n}", "csv", "summary.csv")
    if not os.path.isfile(path):
        return None
    total_e = total_c = ci_e_sq = ci_c_sq = 0.0
    n_dev = None
    found = 0
    with open(path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["Phase"] not in PHASES:
                continue
            nd = int(row["n_devices"])
            if n_dev is None:
                n_dev = nd
            total_e  += float(row["Avg_Energy_mJ"])   * nd
            total_c  += float(row["Avg_CPU_s"])        * nd
            ci_e_sq  += (float(row["CI95_Energy_mJ"]) * nd) ** 2
            ci_c_sq  += (float(row["CI95_CPU_s"])     * nd) ** 2
            found    += 1
    if found == 0 or n_dev is None:
        return None
    return total_e, math.sqrt(ci_e_sq), total_c, math.sqrt(ci_c_sq)


def load_all():
    data = {}   # (scheme, n) -> (e_mJ, ci_e, cpu_s, ci_c) or None
    for s in SCHEMES:
        for n in SIZES:
            data[(s, n)] = load_summary(s, n)
    return data


# ── Plot helpers ──────────────────────────────────────────────────────────────
def _plot_panel(ax, data, metric, ylabel, unit):
    """
    metric: 'energy' or 'cpu'
    Draws grouped bars for each size-group, one bar per scheme.
    """
    n_schemes = len(SCHEMES)
    width     = 0.22
    x_centers = np.arange(len(SIZES))
    offsets   = np.linspace(-(n_schemes - 1) / 2, (n_schemes - 1) / 2, n_schemes) * width

    for si, scheme in enumerate(SCHEMES):
        vals, errs = [], []
        for n in SIZES:
            d = data.get((scheme, n))
            if d is None:
                vals.append(0.0)
                errs.append(0.0)
            elif metric == "energy":
                vals.append(d[0]); errs.append(d[1])
            else:
                vals.append(d[2]); errs.append(d[3])

        ax.bar(
            x_centers + offsets[si], vals, width,
            label=scheme,
            color=COLORS[scheme], hatch=HATCHES[scheme],
            edgecolor="white", linewidth=0.5,
            yerr=errs,
            error_kw=dict(elinewidth=1.2, capsize=3,
                          ecolor="#333333", capthick=1.2),
            zorder=3,
        )

    ax.set_xticks(x_centers)
    ax.set_xticklabels([str(n) for n in SIZES])
    ax.set_xlabel("Network Size (N)")
    ax.set_ylabel(ylabel)
    ax.yaxis.grid(True, zorder=0)
    ax.set_axisbelow(True)
    ax.legend(loc="upper left")


def make_single_panel(data, metric, ylabel, unit, out_path):
    with plt.rc_context(_STYLE):
        fig, ax = plt.subplots(figsize=(8, 5))
        _plot_panel(ax, data, metric, ylabel, unit)
        plt.tight_layout()
        fig.savefig(out_path, dpi=150, bbox_inches="tight")
        plt.close(fig)
    print(f"Saved → {out_path}")


def make_combined(data):
    with plt.rc_context(_STYLE):
        fig, axes = plt.subplots(1, 2, figsize=(14, 5.5))
        _plot_panel(axes[0], data, "energy",
                    "Avg. Energy — all devices (mJ)", "Energy (mJ)")
        _plot_panel(axes[1], data, "cpu",
                    "Avg. CPU Time — all devices (s)", "CPU Time")

        axes[0].set_title("(a) Avg. Energy", fontsize=13)
        axes[1].set_title("(b) Avg. CPU Time", fontsize=13)

        # Remove duplicate legend from right panel
        axes[1].get_legend().remove()

        plt.tight_layout()
        out = os.path.join(OUT, "banerjee_network_variation_combined.png")
        fig.savefig(out, dpi=150, bbox_inches="tight")
        plt.close(fig)
    print(f"Saved → {out}")


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    data = load_all()

    # Print table to stdout
    print(f"\n{'Scheme':12s}  {'N':>5s}  {'Energy(mJ)':>12s}  {'±CI':>8s}  "
          f"{'CPU(s)':>10s}  {'±CI':>8s}")
    print("-" * 65)
    for s in SCHEMES:
        for n in SIZES:
            d = data.get((s, n))
            if d:
                print(f"{s:12s}  {n:>5d}  {d[0]:>12.2f}  {d[1]:>8.2f}  "
                      f"{d[2]:>10.3f}  {d[3]:>8.3f}")
            else:
                print(f"{s:12s}  {n:>5d}  {'MISSING':>12s}")

    # Check if all data is present
    missing = [(s, n) for s in SCHEMES for n in SIZES if data.get((s, n)) is None]
    if missing:
        print(f"\nWARNING: missing data for {missing}")
        print("Run simulations first, then re-run this script.")
        if all(s == "Banerjee" for s, _ in missing):
            print("(Banerjee data only missing — plotting available schemes.)")

    make_single_panel(data, "energy", "Total Energy (mJ)", "Energy",
                      os.path.join(OUT, "banerjee_network_variation_energy.png"))
    make_single_panel(data, "cpu", "Total CPU Time (s)", "CPU Time",
                      os.path.join(OUT, "banerjee_network_variation_cpu.png"))
    make_combined(data)


if __name__ == "__main__":
    main()
